### ISSUE TITLE
Availability of spectral processing binaries

### ISSUE THREAD

**Issue by stevenpawley** [opticks-org/spectral#37]
Thanks for all of your work on Opticks over the years.

The opticks.org website has been down for some time. Although binaries for the latest release are downloadable from the releases page, are the binaries for the spectral processing plugin (for Windows x64) hosted anywhere? It would be really great if those previous 'archive' versions of all of the software and extensions were available somewhere still, even if just in a cloud storage location.

**Comment by tclarke** [comment]
I've uploaded the binaries to a 1.9.0 release. Note that the source tag doesn't quite match (1.9.0 was based on rc3 not rc1) because the tags didn't copy over properly when I imported from Subversion. The binaries are the official release.

**Comment by stevenpawley** [comment]
Thanks for the quick response - this is great and much appreciated!
